# Project Name
TARGET = SYNTHMACHINE

APP_TYPE = BOOT_SRAM

# Sources
CPP_SOURCES = SYNTHMACHINE.cpp

# Library Locations
LIBDAISY_DIR = ../../libDaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
